

export class AudioVisualConstants {
    public static AudioVisualForm = [
        { particulars: 'LED / LCD / PLASMA 32” WITH STAND', 																														qty:'01 SET', code:'001', rate:'1,500-00' },
        { particulars: 'LED / LCD / PLASMA 40” / 42” WITH STAND', 																													qty:'01 SET', code:'002', rate:'2,000-00' },
        { particulars: 'LED / LCD / PLASMA 50” / 52”WITH STAND', 																													qty:'01 SET', code:'003', rate:'3,000-00' },
        { particulars: 'LAPTOP WITH ACCS., CORE I3 WITH O.S.', 																														qty:'01 SET', code:'004', rate:'1,000-00' },
        { particulars: 'DVD PLAYER WITH ACCS.,',																																	qty:'01 SET', code:'005', rate:'250-00' },
        { particulars: 'LED WALL 6mm INDOOR 07ft x 09ft', 																															qty:'01 SET', code:'006', rate:'30,000-00' },
        { particulars: 'LED WALL 6mm INDOOR 08ft x 12ft', 																															qty:'01 SET', code:'007', rate:'40,000-00' },
        { particulars: 'LED WALL 6mm INDOOR 09ft x 16ft', 																															qty:'01 SET', code:'008', rate:'50,000-00' },
        { particulars: 'LED WALL 6mm INDOOR 10ft x 20ft', 																															qty:'01 SET', code:'009', rate:'60,000-00' },
        { particulars: 'LED WALL 6mm INDOOR 12ft x 18ft', 																															qty:'01 SET', code:'010', rate:'65,000-00' },
        { particulars: 'LED WALL 6mm INDOOR 15ft x 15ft', 																															qty:'01 SET', code:'011', rate:'68,000-00' },
        { particulars: 'LED WALL 6mm INDOOR 12ft x 24ft', 																															qty:'01 SET', code:'012', rate:'86,400-00' },
        { particulars: 'DIGITAL STILL CAMERA DIGITAL CAMERA TO CD CONVERTION 1 No.',																								qty:'01 SET', code:'013', rate:'4,000-00' },
        { particulars: 'DIGITAL INSTANT PHOTO\'S (MINIMUM 80 Nos. PHOTO\'S) Rs.60/- EACH.',																							qty:'01 SET', code:'014', rate:'4,000-00' },
        { particulars: 'D V CAMERA (WITH CASEETE & CAMERAMAN)FOR EXTRA CASSETTE 1 hr WITH DVD',																						qty:'01 SET', code:'015', rate:'4,000-00' },
        { particulars: 'MULTIMEDIA SPEAKER', 																																		qty:'01 SET', code:'016', rate:'250-00' },
        { particulars: 'LCD PROJECTOR 1,500 ANSI LUMENS WITH SCREEN.,', 																											qty:'01 SET', code:'017', rate:'1,500-00' },
        { particulars: 'LCD PROJECTOR 2,000 ANSI LUMENS WITH SCREEN.,', 																											qty:'01 SET', code:'018', rate:'1,750-00' },
        { particulars: 'LCD PROJECTOR 3,000 ANSI LUMENS WITH SCREEN.,', 																											qty:'01 SET', code:'019', rate:'2,000-00' },
        { particulars: '4 x 6 / 8 x 6 SCREEN',																																		qty:'01 SET', code:'020', rate:'50-00' },
        { particulars: 'C OMPUTER WITH ACCS., CORE 2 DUO', 																															qty:'01 SET', code:'021', rate:'400-00' },
        { particulars: 'HP LAZER JET PRINTER BLACK', 																																qty:'01 SET', code:'022', rate:'400-00' },
        { particulars: 'HP LAZER JET PRINTER COLOUR', 																																qty:'01 SET', code:'023', rate:'2,500-00' },
        { particulars: 'PAR LIGHT WITH DIMMER', 																																	qty:'01 SET', code:'024', rate:'250-00' },
        { particulars: 'LED PAR LIGHT', 																																			qty:'01 SET', code:'025', rate:'500-00' },
        { particulars: 'CORDLESS COLLER / HAND MIKE', 																																qty:'01 SET', code:'026', rate:'500-00' },
        { particulars: 'PORTABLE P A SYSTEM WITH 1 MIC & 1 AUX INPUT', 																												qty:'01 SET', code:'027', rate:'750-00' },
        { particulars: 'BUILT IN POWER SPEAKER WITH STAND &1 CORDLESS HAND MIC', 																									qty:'',       code:'028', rate:'1,250-00' },
        { particulars: 'P.A. SYSTEM [AHUJA] i. Amplifier 1 No. ii. Speakers 2 Nos.', 																								qty:'01 SET', code:'029', rate:'750-00' },
        { particulars: 'PRO SOUND SYSTEMS WHARFEDALE / TITAN P.A. SYSTEM i. Power Amplifier 1 No. ii. Speakers 2 Nos. iii.Mixer 1 No.',												qty:'01 SET', code:'030', rate:'1,500-00' },
        { particulars: 'BOSE SYSTEM i. BOSE 802 SPEAKERS 2 Nos. ii. POWER AMPLIFIER 1 No. iii. BOSE CONTROLLER 1 No. iv. MIXER 1 No. v. TECHNICIAN',    							qty:'01 SET', code:'031', rate:'2,500-00' },
        { particulars: 'MACKIE SYSTEM i. MACKIE SRM 450 SPEAKERS 2 Nos.ii. POWER AMPLIFIER 1 No.iii. BOSE CONTROLLER 1 No.iv. MIXER 1 No.v. TECHNICIAN', 							qty:'01 SET', code:'032', rate:'4,000-00' },
        { particulars: 'JBL VRX 930 SYSTEM i. JBLVRX 930 SPEAKERS 4 Nos.ii. POWER AMPLIFIER 1 No.iii. JBL CONTROLLER 1 No.iv. MIXER 1 No.v. TECHNICIAN', 							qty:'01 SET', code:'033', rate:'5,000-00' },
        { particulars: 'AUDIO MIXER', 																																				qty:'01 SET', code:'034', rate:'500-00' },
        { particulars: 'TAPE RECORDER', 																																			qty:'01 SET', code:'035', rate:'100-00' },
        { particulars: 'D J SOUND SYSTEM / DAS / JBL - 930 TOP - 04 Nos. DOUBLE BIN - 02 Nos. MIXER -01 No. - 01 No. CONTROLLER - 01 No. CROSSOVER - 01 No. CORDLESS MIC- 01 No.',	qty:'01 SET', code:'036', rate:'10,000-00' }
    ];
}